server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://auth-service-db:5432/${AUTH_SERVICE_DB}
    username: ${AUTH_SERVICE_USER}
    password: ${AUTH_SERVICE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/majheriserve

keycloak:
  admin:
    server-uri: http://localhost:9090
    realm: majheriserve # The realm that our admin client will manage
    client-id: majheriserve-backend-admin # A confidential client with a service account for our auth-service to programmatically manage Keycloak resources
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        security: DEBUG
